# Generated by Django 4.0.5 on 2023-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=100)),
                ('rollNo', models.CharField(max_length=20)),
                ('ownerEmail', models.EmailField(max_length=254)),
                ('accessCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='StreamPlatform',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
