# Generated by Django 4.0.5 on 2023-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_remove_company_accesscode_company_secret_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='secret_code',
        ),
        migrations.AddField(
            model_name='company',
            name='accessCode',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
